// <auto-generated />
namespace Casino.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class testThe_discardBool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testThe_discardBool));
        
        string IMigrationMetadata.Id
        {
            get { return "202103020359031_testThe_discardBool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
