// <auto-generated />
namespace Casino.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class anotherForce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(anotherForce));
        
        string IMigrationMetadata.Id
        {
            get { return "202103080552234_anotherForce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
