// <auto-generated />
namespace Casino.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class After1237push : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(After1237push));
        
        string IMigrationMetadata.Id
        {
            get { return "202102210552522_After1237push"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
